// ============================================================================
// KIZUNA v2 — "Threads" card prototype.
//
// Design thesis (from the v2 notes): THE PARTY IS THE CHARACTER.  You are not
// controlling Cassia — you are controlling the Kizuna between three people.
//
//  · Cards are the expression layer; formation + relationships are the game.
//  · Each hero carries 1 Core + 1 Signature card, both re-written by the row
//    they stand in (front/mid/back = aggressive/balanced/ranged) — plus
//    0-2 temporary cards generated by the state of the battle.
//  · Resonance is EMERGENT, not a meter: helping an ally (heal / guard /
//    inspire) forms a visible thread between the two.  Close a full triangle
//    of threads and the battlefield freezes — TRIAD FORMED — and a resonant
//    card burns into your hand.  Which card depends on the CLASS composition
//    of the triangle (procedural table below).
//  · Resonant outcomes span Offense / Defense / Formation / Utility.
//  · Onboarding is Portal-shaped: Ch1 one hero (rows = stances), Ch2 two
//    heroes (swapping, protection, first threads), Ch3 three heroes
//    (triangles, discovered — never "unlocked" — team attacks).
//
// Combat model (per the combat-overview mock): EP energy pays for cards,
// cards resolve INSTANTLY with feedback, END TURN passes to the enemies,
// a turn-order timeline runs across the top, and enemy intents always
// telegraph damage + the lane they'll strike.
// ============================================================================

'use strict';

const V2_BUILD = 1;
const $ = (sel) => document.querySelector(sel);

// ---------------------------------------------------------------------------
// DATA — heroes.  Rows re-write each hero's two cards (stance system).
// target: 'frontmost' | 'enemy' (pick) | 'ally' (pick) | 'self' | 'allies'
// ---------------------------------------------------------------------------
const ROWS = ['front', 'mid', 'back'];
const ROW_LABEL = { front: 'FRONT', mid: 'MID', back: 'BACK' };
const STANCE = {
  front: { name: 'Blade Stance', tag: 'AGGRESSIVE' },
  mid:   { name: 'Flow Stance',  tag: 'BALANCED' },
  back:  { name: 'Wind Stance',  tag: 'RANGED' },
};

const HEROES = {
  ash: {
    name: 'ASH', cls: 'Ronin', tint: 'var(--ash-tint)', maxHp: 32,
    cards: {
      front: {
        core: { name: 'Cleave',        cost: 1, target: 'frontmost', fx: { dmg: 6 },            desc: '6 damage to the nearest enemy.' },
        sig:  { name: 'Crashing Wave', cost: 2, target: 'frontmost', fx: { dmg: 11 },           desc: '11 damage to the nearest enemy.' },
      },
      mid: {
        core: { name: 'Flowing Cut',   cost: 1, target: 'frontmost', fx: { dmg: 4, guard: 3 },  desc: '4 damage · gain 3 guard.' },
        sig:  { name: 'Riposte',       cost: 2, target: 'self',      fx: { guard: 7, counter: 5 }, desc: 'Gain 7 guard · counter attackers for 5 this round.' },
      },
      back: {
        core: { name: 'Thrown Edge',   cost: 1, target: 'enemy',     fx: { dmg: 4 },            desc: '4 damage to ANY enemy.' },
        sig:  { name: 'Marked Fate',   cost: 2, target: 'enemy',     fx: { dmg: 3, mark: 3 },   desc: '3 damage · MARK: enemy takes +3 from every hit this round.' },
      },
    },
  },
  elin: {
    name: 'ELIN', cls: 'Cleric', tint: 'var(--elin-tint)', maxHp: 24,
    cards: {
      front: {
        core: { name: 'Smite',         cost: 1, target: 'frontmost', fx: { dmg: 4 },            desc: '4 holy damage to the nearest enemy.' },
        sig:  { name: 'Radiant Ward',  cost: 2, target: 'allies',    fx: { guard: 3 },          desc: 'Every ally gains 3 guard.' },
      },
      mid: {
        core: { name: 'Mend',          cost: 1, target: 'ally',      fx: { heal: 5 },           desc: 'Heal an ally 5.' },
        sig:  { name: 'Sanctuary',     cost: 2, target: 'ally',      fx: { heal: 4, guard: 4 }, desc: 'Heal an ally 4 · they gain 4 guard.' },
      },
      back: {
        core: { name: 'Distant Prayer',cost: 1, target: 'allies',    fx: { heal: 2 },           desc: 'Heal every ally 2.' },
        sig:  { name: 'Benediction',   cost: 2, target: 'ally',      fx: { heal: 8 },           desc: 'Heal an ally 8.' },
      },
    },
  },
  kiki: {
    name: 'KIKI', cls: 'Bard', tint: 'var(--kiki-tint)', maxHp: 20,
    cards: {
      front: {
        core: { name: 'Sharp Note',    cost: 1, target: 'frontmost', fx: { dmg: 3, lull: 1 },   desc: '3 damage · enemy deals −1 next attack.' },
        sig:  { name: 'Discord',       cost: 2, target: 'enemy',     fx: { dmg: 5, lull: 2 },   desc: '5 damage to ANY enemy · −2 next attack.' },
      },
      mid: {
        core: { name: 'Inspire',       cost: 1, target: 'ally',      fx: { buffDmg: 3 },        desc: 'An ally’s next damaging card deals +3.' },
        sig:  { name: 'Battle Hymn',   cost: 2, target: 'allies',    fx: { buffDmg: 2 },        desc: 'Every ally’s next damaging card deals +2.' },
      },
      back: {
        core: { name: 'Lullaby',       cost: 1, target: 'enemy',     fx: { lull: 2 },           desc: 'An enemy deals −2 on its next attack.' },
        sig:  { name: 'Crescendo',     cost: 2, target: 'ally',      fx: { buffDmg: 5 },        desc: 'An ally’s next damaging card deals +5.' },
      },
    },
  },
};

// ---------------------------------------------------------------------------
// DATA — enemies.  Intents cycle; each telegraphs damage + the PARTY ROW it
// will strike.  An intent that finds no hero in its row simply misses — in
// Chapter 1 that IS the dodge mechanic (stances are also positions).
// ---------------------------------------------------------------------------
const ENEMY_DEFS = {
  husk: {
    name: 'HOLLOW HUSK', maxHp: 13,
    intents: [
      { name: 'Claw',  dmg: 4, row: 'front' },
      { name: 'Lurch', dmg: 3, row: 'mid' },
      { name: 'Wither', kind: 'buff', desc: 'hardens', guardSelf: 3 },
    ],
  },
  wraith: {
    name: 'PALE WRAITH', maxHp: 16,
    intents: [
      { name: 'Grasp Beyond', dmg: 5, row: 'back' },
      { name: 'Chill Wail',   dmg: 2, row: 'all' },
      { name: 'Drift',        dmg: 4, row: 'mid' },
    ],
  },
  cultist: {
    name: 'ASH CULTIST', maxHp: 15,
    intents: [
      { name: 'Sacrificial Knife', dmg: 5, row: 'front' },
      { name: 'Blood Chant', kind: 'buff', desc: 'gathers power', powerSelf: 2 },
      { name: 'Hollow Verse', dmg: 4, row: 'mid' },
    ],
  },
  echoknight: {
    name: 'THE ECHO KNIGHT', maxHp: 42, boss: true,
    intents: [
      { name: 'Returning Stroke', dmg: 6, row: 'front' },
      { name: 'Echoed Arc',       dmg: 4, row: 'mid' },
      { name: 'Remembered Blade', dmg: 5, row: 'back' },
      { name: 'OBLIVION ECHO',    dmg: 8, row: 'all', heavy: true },
    ],
  },
};

// ---------------------------------------------------------------------------
// DATA — procedural resonant cards, keyed by the sorted class-triple of the
// triangle.  Four outcome families: Offense / Defense / Formation / Utility.
// ---------------------------------------------------------------------------
const RESONANT_TABLE = {
  'Bard+Cleric+Ronin': {
    name: 'Threefold Vow', type: 'Offense',
    desc: 'Three-stage combo: Ash strikes ALL enemies 8 · Elin heals the party 6 · Kiki grants the party 5 guard.',
    stages: [
      { actor: 'ash',  text: 'Ash cuts through every line',      fx: { aoeDmg: 8 } },
      { actor: 'elin', text: 'Elin’s light closes every wound',  fx: { healAll: 6 } },
      { actor: 'kiki', text: 'Kiki’s song turns to armor',       fx: { guardAll: 5 } },
    ],
  },
  // Documented futures (per the v2 notes):
  'Cleric+Guardian+Bard':       { name: 'Divine Bastion', type: 'Defense',   desc: 'Front row becomes invulnerable for a turn; enemies retarget.' },
  'Assassin+Guardian+Mage':     { name: 'Shadow Nova',    type: 'Offense',   desc: 'Detonate from the shadow of the shield.' },
  'Guardian+Guardian+Guardian': { name: 'Iron Phalanx',   type: 'Formation', desc: 'The wall advances one row; enemies are pushed back.' },
};
const RESONANT_FALLBACK = {
  name: 'Triad Strike', type: 'Offense',
  desc: 'The three strike as one: 6 damage to every enemy.',
  stages: [{ actor: null, text: 'The triad strikes as one', fx: { aoeDmg: 6 } }],
};

// ---------------------------------------------------------------------------
// DATA — the slice's flow: story beats and fights, in order.
// ---------------------------------------------------------------------------
const FLOW = [
  { type: 'story', chapter: 1, title: 'ONE SURVIVOR', eyebrow: 'CHAPTER 1', lines: [
    { text: 'The first thing you understand is that everyone else is gone.' },
    { spk: 'ASH', text: '...then I carry it alone.' },
    { text: 'You are <b>Ash</b>. One blade, three ways to hold it. Your <b>row is your stance</b> — Front cuts, Mid flows, Back strikes from the wind. Your cards change when you move.' },
  ]},
  { type: 'fight', chapter: 1, heroes: ['ash'], enemies: ['husk'],
    narrator: 'Tap a card to play it. EP pays for cards. END TURN when spent.' },
  { type: 'story', chapter: 1, title: 'THE STANCES', eyebrow: 'CHAPTER 1', lines: [
    { text: 'More of them ahead. Watch what each enemy <b>telegraphs</b>: the damage, and the <b>row</b> it will strike.' },
    { spk: 'ASH', text: 'If the blow falls on FRONT... I simply won’t be there.' },
    { text: 'Use <b>Shift Stance</b> to change rows. An attack on an empty row hits nothing.' },
  ]},
  { type: 'fight', chapter: 1, heroes: ['ash'], enemies: ['husk', 'wraith'],
    narrator: 'Dodge by standing elsewhere. The row they call is the row they strike.' },
  { type: 'story', chapter: 2, title: 'ELIN', eyebrow: 'CHAPTER 2 · TWO', lines: [
    { text: 'A light in the ash-fog. A healer, kneeling over what’s left of her order.' },
    { spk: 'ELIN', text: 'You’re bleeding. Stand still.' },
    { spk: 'ASH', text: '...you’re coming with me.' },
    { text: 'Two now. Movement becomes <b>swapping</b>. And watch what happens when one of you <b>helps</b> the other.' },
  ]},
  { type: 'fight', chapter: 2, heroes: ['ash', 'elin'], enemies: ['cultist', 'husk'],
    narrator: 'When Elin heals Ash, something forms between them. Watch.' },
  { type: 'story', chapter: 3, title: 'KIKI', eyebrow: 'CHAPTER 3 · THREE', lines: [
    { text: 'Someone is singing. In this place. Singing.' },
    { spk: 'KIKI', text: 'Oh good, an audience! Try to die interestingly, at least.' },
    { text: 'Three now. Threads can close into something greater. No one will tell you how. You’ll know it when it happens.' },
  ]},
  { type: 'fight', chapter: 3, heroes: ['ash', 'elin', 'kiki'], enemies: ['echoknight', 'cultist'],
    narrator: 'Help each other. All three of you.' },
  { type: 'story', chapter: 3, title: 'END OF THE SLICE', eyebrow: 'KIZUNA V2', lines: [
    { text: 'That’s the vertical slice: <b>one hero → stances</b>, <b>two → swapping and threads</b>, <b>three → the triangle</b>.' },
    { text: 'Beyond this: procedural resonant cards per class-triangle (Defense, Formation and Utility outcomes — not just damage), temporary cards from equipment and relics, and the full descent.' },
    { spk: 'KIKI', text: 'We’re keeping the singing, right?' },
  ], end: true },
];

// ---------------------------------------------------------------------------
// STATE
// ---------------------------------------------------------------------------
let S = null;               // battle state
let flowIdx = 0;
let targeting = null;       // { card, validIds } while picking a target
const PROGRESS_KEY = 'kizuna2.flow';
const UNLOCK_KEY = 'kizuna.unlocked';   // shared with v1

function newBattle(node) {
  const heroes = node.heroes.map((id, i) => ({
    id, def: HEROES[id],
    hp: HEROES[id].maxHp, maxHp: HEROES[id].maxHp,
    row: ['front', 'mid', 'back'][i] || 'front',
    guard: 0, buffDmg: 0, counter: 0, downed: false,
  }));
  const enemies = node.enemies.map((id, i) => ({
    id, def: ENEMY_DEFS[id], uid: id + '#' + i,
    hp: ENEMY_DEFS[id].maxHp, maxHp: ENEMY_DEFS[id].maxHp,
    row: ['front', 'mid', 'back'][i] || 'mid',
    guard: 0, power: 0, mark: 0, lull: 0, intentIdx: 0, dead: false, acted: false,
  }));
  return {
    node, heroes, enemies,
    maxEp: 2 + heroes.length, ep: 2 + heroes.length,
    used: new Set(),                 // 'heroId:kind' spent this turn
    threads: new Set(),              // 'a|b' sorted pair keys
    triadFormed: false, resonantUsed: false, resonantNew: false,
    executing: false, over: false, turn: 1,
  };
}

const pairKey = (a, b) => [a, b].sort().join('|');
const livingHeroes = () => S.heroes.filter(h => !h.downed);
const livingEnemies = () => S.enemies.filter(e => !e.dead);
const heroInRow = (row) => livingHeroes().find(h => h.row === row) || null;
const frontmostEnemy = () => ['front', 'mid', 'back'].map(r => livingEnemies().find(e => e.row === r)).find(Boolean) || livingEnemies()[0] || null;

// ---------------------------------------------------------------------------
// HAND — rebuilt every render.  1 Core + 1 Signature + Move per hero, plus a
// resonant card once the triangle closes.  Spent cards stay visible, grayed.
// ---------------------------------------------------------------------------
function cardType(card) {
  if (card.kind === 'resonant') return 'resonant';
  if (card.kind === 'move') return 'move';
  const fx = card.fx || {};
  if (fx.dmg) return 'attack';
  if (fx.guard || fx.counter) return 'guard';
  return 'skill';
}
function buildHand() {
  const hand = [];
  livingHeroes().forEach(h => {
    const set = h.def.cards[h.row];
    hand.push(mkCard(h, 'core', set.core));
    hand.push(mkCard(h, 'sig', set.sig));
    hand.push(mkMoveCard(h));
  });
  if (S.triadFormed && !S.resonantUsed) hand.push(mkResonantCard());
  return hand;
}
function mkCard(h, kind, def) {
  return { kind, owner: h.id, ownerName: h.def.name, tint: h.def.tint,
    stance: STANCE[h.row].name, name: def.name, cost: def.cost, target: def.target, fx: def.fx, desc: def.desc,
    spent: S.used.has(h.id + ':' + kind) };
}
function mkMoveCard(h) {
  const solo = livingHeroes().length === 1;
  return { kind: 'move', owner: h.id, ownerName: h.def.name, tint: h.def.tint,
    stance: STANCE[h.row].name, name: solo ? 'Shift Stance' : 'Reposition', cost: 1, target: 'row',
    desc: solo ? 'Move to another row — your cards change with your stance.'
               : 'Move to another row (swap with whoever stands there).',
    spent: S.used.has(h.id + ':move') };
}
function triadEntry() {
  const classes = livingHeroes().map(h => h.def.cls).sort().join('+');
  return RESONANT_TABLE[classes] && RESONANT_TABLE[classes].stages ? RESONANT_TABLE[classes] : RESONANT_FALLBACK;
}
function mkResonantCard() {
  const r = triadEntry();
  return { kind: 'resonant', owner: 'triad', ownerName: 'THE TRIAD', tint: 'var(--gold-bright)',
    stance: r.type.toUpperCase(), name: r.name, cost: S.maxEp, target: 'none', fx: { resonant: true },
    desc: r.desc + '  Consumes your entire turn.', spent: false };
}

// ---------------------------------------------------------------------------
// PLAY — instant resolution (mock flow: choose → target → resolve).
// ---------------------------------------------------------------------------
function onCardTap(card) {
  if (S.executing || S.over || card.spent) return;
  if (card.cost > S.ep) { flashNarrator('Not enough EP.'); return; }
  if (card.kind === 'resonant' && S.ep < S.maxEp) {
    flashNarrator('The Vow needs your ENTIRE turn — play it first.');
    return;
  }
  if (card.target === 'enemy') { enterTargeting(card, livingEnemies().map(e => e.uid), 'Choose an enemy'); return; }
  if (card.target === 'ally') {
    const others = livingHeroes().filter(h => h.id !== card.owner).map(h => h.id);
    const ids = others.length ? others : livingHeroes().map(h => h.id);
    enterTargeting(card, ids, 'Choose an ally'); return;
  }
  if (card.target === 'row') { enterRowPick(card); return; }
  playCard(card, null);
}
function enterTargeting(card, validIds, hint) {
  targeting = { card, validIds };
  $('#target-hint').textContent = hint + ' — tap a figure';
  $('#target-hint').classList.remove('hidden');
  renderAll();
}
function cancelTargeting() {
  targeting = null;
  $('#target-hint').classList.add('hidden');
  renderAll();
}
function onFigureTap(id) {
  if (!targeting || targeting.isRow) return;
  if (!targeting.validIds.includes(id)) { cancelTargeting(); return; }
  const card = targeting.card;
  targeting = null;
  $('#target-hint').classList.add('hidden');
  playCard(card, id);
}
function enterRowPick(card) {
  const owner = S.heroes.find(h => h.id === card.owner);
  const rows = ROWS.filter(r => r !== owner.row);
  targeting = { card, validIds: rows.map(r => 'row:' + r), isRow: true };
  $('#target-hint').textContent = 'Move ' + card.ownerName + ' to — tap a row';
  $('#target-hint').classList.remove('hidden');
  renderAll();
}
function onRowTap(row) {
  if (!targeting || !targeting.isRow) return;
  const card = targeting.card;
  if (!targeting.validIds.includes('row:' + row)) { cancelTargeting(); return; }
  targeting = null;
  $('#target-hint').classList.add('hidden');
  playCard(Object.assign({}, card, { toRow: row }), null);
}

async function playCard(card, targetId) {
  if (S.executing || S.over) return;
  S.executing = true;
  $('#stage').classList.add('executing');
  S.ep -= card.cost;
  if (card.owner !== 'triad') S.used.add(card.owner + ':' + card.kind);
  renderAll();
  await resolveCard(card, targetId);
  S.executing = false;
  $('#stage').classList.remove('executing');
  renderAll();
  checkEnd();
}

const sleep = (ms) => new Promise(r => setTimeout(r, ms));

async function resolveCard(card, targetId) {
  const owner = S.heroes.find(h => h.id === card.owner);
  if (owner && owner.downed) return;

  if (card.kind === 'move') {
    const from = owner.row;
    const occupant = livingHeroes().find(h => h.id !== owner.id && h.row === card.toRow);
    owner.row = card.toRow;
    if (occupant) { occupant.row = from; }
    renderAll();
    popupAt(figEl(owner.id), STANCE[card.toRow].name.toUpperCase(), 'info');
    if (occupant) popupAt(figEl(occupant.id), 'SWAP', 'info');
    await sleep(340);
    return;
  }

  if (card.kind === 'resonant') { await resolveResonant(); return; }

  const fx = card.fx || {};
  if (fx.dmg) {
    let tgt = null;
    if (card.target === 'frontmost') tgt = frontmostEnemy();
    else if (card.target === 'enemy') tgt = livingEnemies().find(e => e.uid === targetId) || frontmostEnemy();
    if (tgt) {
      let amt = fx.dmg + (owner ? owner.buffDmg : 0);
      if (owner && owner.buffDmg) { popupAt(figEl(owner.id), '+' + owner.buffDmg, 'guard'); owner.buffDmg = 0; }
      amt += tgt.mark || 0;
      dealToEnemy(tgt, amt);
    } else {
      flashNarrator('No target in reach — the cut finds only air.');
    }
  }
  if (fx.mark) {
    const tgt = livingEnemies().find(e => e.uid === targetId);
    if (tgt) { tgt.mark = fx.mark; popupAt(figEl(tgt.uid), 'MARKED', 'info'); }
  }
  if (fx.lull) {
    const tgt = card.target === 'enemy' ? (livingEnemies().find(e => e.uid === targetId) || frontmostEnemy()) : frontmostEnemy();
    if (tgt) { tgt.lull = (tgt.lull || 0) + fx.lull; popupAt(figEl(tgt.uid), '−' + fx.lull + ' ATK', 'info'); }
  }
  // --- helping (thread-forming when it lands on a single OTHER ally) ---
  if (fx.heal || fx.guard || fx.buffDmg || fx.counter) {
    let receivers = [];
    if (card.target === 'ally')   receivers = [S.heroes.find(h => h.id === targetId)].filter(Boolean);
    if (card.target === 'self')   receivers = [owner];
    if (card.target === 'allies') receivers = livingHeroes();
    if (card.target === 'frontmost' && fx.guard) receivers = [owner];  // e.g. Flowing Cut's self-guard
    for (const rc of receivers) {
      if (!rc || rc.downed) continue;
      if (fx.heal)   { rc.hp = Math.min(rc.maxHp, rc.hp + fx.heal); popupAt(figEl(rc.id), '+' + fx.heal, 'heal'); }
      if (fx.guard)  { rc.guard += fx.guard; popupAt(figEl(rc.id), '⛨ ' + fx.guard, 'guard'); }
      if (fx.buffDmg){ rc.buffDmg += fx.buffDmg; popupAt(figEl(rc.id), '+' + fx.buffDmg + ' NEXT', 'guard'); }
      if (fx.counter){ rc.counter = Math.max(rc.counter, fx.counter); }
      // The Kizuna rule: a deliberate, personal act of help forms a thread.
      if (owner && rc.id !== owner.id && card.target === 'ally') await addThread(owner.id, rc.id);
    }
  }
  await sleep(280);
}

function dealToEnemy(e, amt) {
  let left = amt;
  if (e.guard > 0) { const g = Math.min(e.guard, left); e.guard -= g; left -= g; }
  e.hp = Math.max(0, e.hp - left);
  popupAt(figEl(e.uid), '−' + amt, 'dmg');
  shake(figEl(e.uid));
  if (e.hp === 0) { e.dead = true; }
}

async function addThread(a, b) {
  const key = pairKey(a, b);
  if (S.threads.has(key)) return;
  S.threads.add(key);
  renderThreads(key);
  flashNarrator('A thread forms — ' + HEROES[a].name + ' ─ ' + HEROES[b].name);
  const live = livingHeroes();
  if (live.length >= 3 && !S.triadFormed) {
    const [x, y, z] = live.map(h => h.id);
    if (S.threads.has(pairKey(x, y)) && S.threads.has(pairKey(y, z)) && S.threads.has(pairKey(x, z))) {
      S.triadFormed = true;
      await triadCeremony();
    }
  }
}

// The discovery moment: the battlefield freezes, the triangle draws itself,
// and a card burns into existence.  Never announced beforehand.
async function triadCeremony() {
  $('#stage').classList.add('frozen');
  await sleep(700);
  const r = triadEntry();
  const names = livingHeroes().map(h => h.def.name).join(' · ');
  showOverlay(`
    <svg class="triad-svg" viewBox="0 0 150 130">
      <path d="M 75 12 L 138 112 L 12 112 Z"/>
    </svg>
    <div class="triad-title">TRIAD FORMED</div>
    <div class="triad-names">${names}</div>
    <div class="triad-cardname">✦ ${r.name} — ${r.type}</div>
    <div class="ov-tap">a card burns into your hand · tap to continue</div>
  `, 'triad-ceremony');
  await new Promise(res => { $('#overlay').onclick = () => { $('#overlay').onclick = null; res(); }; });
  hideOverlay();
  $('#stage').classList.remove('frozen');
  S.resonantNew = true;
  renderAll();
}

async function resolveResonant() {
  const r = triadEntry();
  S.resonantUsed = true;
  for (const st of (r.stages || [])) {
    flashNarrator('✦ ' + st.text);
    const fx = st.fx || {};
    if (fx.aoeDmg) livingEnemies().forEach(e => dealToEnemy(e, fx.aoeDmg + (e.mark || 0)));
    if (fx.healAll) livingHeroes().forEach(h => { h.hp = Math.min(h.maxHp, h.hp + fx.healAll); popupAt(figEl(h.id), '+' + fx.healAll, 'heal'); });
    if (fx.guardAll) livingHeroes().forEach(h => { h.guard += fx.guardAll; popupAt(figEl(h.id), '⛨ ' + fx.guardAll, 'guard'); });
    renderAll();
    await sleep(800);
    if (checkEnd()) return;
  }
}

// ---------------------------------------------------------------------------
// END TURN → enemy phase → next turn
// ---------------------------------------------------------------------------
async function endTurn() {
  if (S.executing || S.over) return;
  S.executing = true;
  $('#stage').classList.add('executing');
  renderAll();
  await enemyPhase();
  if (!S.over) {
    S.turn++;
    S.ep = S.maxEp;
    S.used = new Set();
    S.heroes.forEach(h => { h.guard = 0; h.counter = 0; });
    S.enemies.forEach(e => { e.mark = 0; e.acted = false; });
    S.executing = false;
    $('#stage').classList.remove('executing');
    renderAll();
  }
}

async function enemyPhase() {
  for (const e of livingEnemies()) {
    if (S.over) break;
    const intent = e.def.intents[e.intentIdx % e.def.intents.length];
    e.intentIdx++;
    e.acted = true;
    renderTimeline();
    await sleep(430);
    if (intent.kind === 'buff') {
      if (intent.guardSelf) { e.guard += intent.guardSelf; popupAt(figEl(e.uid), '⛨ ' + intent.guardSelf, 'guard'); }
      if (intent.powerSelf) { e.power += intent.powerSelf; popupAt(figEl(e.uid), '+' + intent.powerSelf + ' ATK', 'info'); }
      renderAll();
      continue;
    }
    let dmg = Math.max(0, (intent.dmg || 0) + (e.power || 0) - (e.lull || 0));
    if (e.lull) e.lull = 0;
    const rows = intent.row === 'all' ? ROWS.slice() : [intent.row];
    let hitAny = false;
    for (const row of rows) {
      const h = heroInRow(row);
      if (!h) continue;
      hitAny = true;
      let left = dmg;
      if (h.guard > 0) { const g = Math.min(h.guard, left); h.guard -= g; left -= g; popupAt(figEl(h.id), '⛨', 'guard'); }
      if (left > 0) {
        h.hp = Math.max(0, h.hp - left);
        popupAt(figEl(h.id), '−' + left, 'dmg');
        shake(figEl(h.id));
      }
      if (h.counter > 0 && !e.dead) { dealToEnemy(e, h.counter); flashNarrator(h.def.name + ' counters!'); }
      if (h.hp === 0) { h.downed = true; popupAt(figEl(h.id), 'DOWN', 'dmg'); }
    }
    if (!hitAny) {
      popupAt(figEl(e.uid), 'MISS', 'info');
      flashNarrator(e.def.name + '’s ' + intent.name + ' finds an empty row.');
    }
    renderAll();
    await sleep(400);
    if (checkEnd()) break;
  }
}

function checkEnd() {
  if (S.over) return true;
  if (!livingEnemies().length) { S.over = true; onVictory(); return true; }
  if (!livingHeroes().length) { S.over = true; onDefeat(); return true; }
  return false;
}

function onVictory() {
  setTimeout(() => {
    showOverlay(`
      <div class="ov-eyebrow" style="color:var(--gold-bright)">VICTORY</div>
      <div class="ov-title" style="font-size:22px">THE ROAD HOLDS</div>
      <button class="ov-btn primary" id="ov-next">CONTINUE</button>
    `);
    $('#ov-next').onclick = () => { hideOverlay(); advanceFlow(); };
  }, 700);
}
function onDefeat() {
  setTimeout(() => {
    showOverlay(`
      <div class="ov-eyebrow">DEFEAT</div>
      <div class="ov-title" style="font-size:22px">THE THREAD FRAYS</div>
      <div class="ov-sub">but does not break</div>
      <button class="ov-btn primary" id="ov-retry">TRY AGAIN</button>
    `);
    $('#ov-retry').onclick = () => { hideOverlay(); startFlowNode(); };
  }, 700);
}

// ---------------------------------------------------------------------------
// FLOW
// ---------------------------------------------------------------------------
function advanceFlow() {
  flowIdx++;
  try { localStorage.setItem(PROGRESS_KEY, String(flowIdx)); } catch (_) {}
  startFlowNode();
}
function startFlowNode() {
  const node = FLOW[flowIdx];
  if (!node) { flowIdx = 0; showTitle(); return; }
  $('#chapter-chip').textContent = 'CH ' + (node.chapter || 1);
  if (node.type === 'story') showStory(node);
  else startFight(node);
}
function startFight(node) {
  S = newBattle(node);
  hideOverlay();
  flashNarrator(node.narrator || '');
  renderAll();
}

// Story beats reveal one line per tap (the v1 sequential-vignette pattern).
function showStory(node) {
  let revealed = 1;
  const render = () => {
    const linesHtml = node.lines.slice(0, revealed).map(l =>
      `<div class="ov-line">${l.spk ? `<span class="spk">${l.spk}</span>` : ''}${l.text}</div>`).join('');
    const done = revealed >= node.lines.length;
    showOverlay(`
      <div class="ov-eyebrow">${node.eyebrow || ''}</div>
      <div class="ov-title" style="font-size:24px">${node.title}</div>
      <div class="ov-lines">${linesHtml}</div>
      ${done
        ? (node.end
            ? `<button class="ov-btn primary" id="ov-go">BACK TO TITLE</button>
               <div class="ov-hint">V1 REMAINS AT THE ROOT — THIS IS THE V2 PROTOTYPE</div>`
            : `<button class="ov-btn primary" id="ov-go">${FLOW[flowIdx + 1] && FLOW[flowIdx + 1].type === 'fight' ? 'TO BATTLE' : 'CONTINUE'}</button>`)
        : `<div class="ov-tap">tap to continue ▸</div>`}
    `);
    if (done) {
      $('#ov-go').onclick = (ev) => {
        ev.stopPropagation();
        if (node.end) { flowIdx = 0; try { localStorage.setItem(PROGRESS_KEY, '0'); } catch (_) {} showTitle(); }
        else { hideOverlay(); advanceFlow(); }
      };
    } else {
      $('#overlay').onclick = () => { $('#overlay').onclick = null; revealed++; render(); };
    }
  };
  render();
}

// ---------------------------------------------------------------------------
// RENDER
// ---------------------------------------------------------------------------
function figEl(id) { return document.querySelector(`[data-fig="${id}"]`); }

function renderAll() {
  if (!S) return;
  renderTimeline();
  renderBattlefield();
  renderThreads();
  renderActionBar();
}

// Turn-order timeline (mock: portrait diamonds around a turn counter —
// party acts first, then each living enemy in row order).
function renderTimeline() {
  const tl = $('#timeline');
  if (!S) { tl.innerHTML = ''; return; }
  const bits = [];
  livingHeroes().forEach(h => {
    bits.push(`<div class="tl-diamond tl-hero"><div class="tl-art">${V2PORTRAITS[h.id] || ''}</div></div>`);
  });
  bits.push(`<div class="tl-turn"><span>${S.turn}</span></div>`);
  livingEnemies().forEach(e => {
    bits.push(`<div class="tl-diamond tl-enemy${e.acted ? ' tl-acted' : ''}"><div class="tl-art">${V2PORTRAITS[e.id] || ''}</div></div>`);
  });
  tl.innerHTML = bits.join('');
}

function renderBattlefield() {
  const telegraphed = new Set();
  livingEnemies().forEach(e => {
    const it = e.def.intents[e.intentIdx % e.def.intents.length];
    if (it.row === 'all') ROWS.forEach(r => telegraphed.add(r));
    else if (it.row) telegraphed.add(it.row);
  });

  const party = $('#party-half');
  party.innerHTML = '';
  // party rendered back→front left-to-right so FRONT faces the enemies
  ['back', 'mid', 'front'].forEach(row => {
    const slot = document.createElement('div');
    slot.className = 'slot' + (telegraphed.has(row) ? ' slot-telegraphed' : '');
    slot.dataset.row = row;
    const h = S.heroes.find(x => x.row === row && !x.downed);
    const downedHere = S.heroes.find(x => x.row === row && x.downed);
    slot.innerHTML = `<span class="slot-ring"></span>`;
    const who = h || downedHere;
    if (who) {
      const fig = document.createElement('div');
      fig.className = 'figure party' + (who.downed ? ' downed' : '');
      fig.dataset.fig = who.id;
      const solo = livingHeroes().length === 1;
      const targetable = targeting && !targeting.isRow && targeting.validIds.includes(who.id);
      if (targetable) fig.classList.add('fig-targetable');
      fig.innerHTML = `
        ${solo ? `<span class="stance-tag">${STANCE[who.row].name.toUpperCase()}</span>` : ''}
        <div class="fig-art">${V2PORTRAITS[who.id] || ''}</div>
        <div class="fig-chips">
          ${who.guard ? `<span class="chip guard">⛨ ${who.guard}</span>` : ''}
          ${who.buffDmg ? `<span class="chip buff">+${who.buffDmg}</span>` : ''}
          ${who.counter ? `<span class="chip counter">↺ ${who.counter}</span>` : ''}
        </div>
        <div class="hp-bar"><div class="hp-fill" style="width:${(who.hp / who.maxHp) * 100}%"></div></div>
        <div class="fig-name">${who.def.name} <span class="hp-num">${who.hp}/${who.maxHp}</span></div>
      `;
      fig.onclick = () => onFigureTap(who.id);
      slot.appendChild(fig);
    }
    const lbl = document.createElement('span');
    lbl.className = 'slot-label';
    lbl.textContent = ROW_LABEL[row];
    slot.appendChild(lbl);
    if (targeting && targeting.isRow && targeting.validIds.includes('row:' + row)) {
      slot.style.cursor = 'pointer';
      slot.querySelector('.slot-ring').style.borderColor = 'var(--gold-bright)';
      slot.onclick = () => onRowTap(row);
    }
    party.appendChild(slot);
  });

  const enemyHalf = $('#enemy-half');
  enemyHalf.innerHTML = '';
  ['front', 'mid', 'back'].forEach(row => {
    const slot = document.createElement('div');
    slot.className = 'slot';
    slot.dataset.row = row;
    const e = S.enemies.find(x => x.row === row && !x.dead);
    if (e) {
      const it = e.def.intents[e.intentIdx % e.def.intents.length];
      const fig = document.createElement('div');
      fig.className = 'figure enemy';
      fig.dataset.fig = e.uid;
      const targetable = targeting && !targeting.isRow && targeting.validIds.includes(e.uid);
      if (targetable) fig.classList.add('fig-targetable');
      const intentHtml = it.kind === 'buff'
        ? `<div class="intent intent-buff"><span>◈</span><span class="i-row">${it.desc || 'gathers'}</span></div>`
        : `<div class="intent${it.heavy ? ' intent-heavy' : ''}"><span>⚔</span><span class="i-dmg">${Math.max(0, (it.dmg || 0) + (e.power || 0) - (e.lull || 0))}</span><span class="i-row">→ ${it.row === 'all' ? 'ALL' : ROW_LABEL[it.row]}</span></div>`;
      fig.innerHTML = `
        ${intentHtml}
        <div class="fig-art">${V2PORTRAITS[e.id] || ''}</div>
        <div class="fig-chips">
          ${e.guard ? `<span class="chip guard">⛨ ${e.guard}</span>` : ''}
          ${e.power ? `<span class="chip buff">+${e.power}</span>` : ''}
          ${e.mark ? `<span class="chip mark">✕ ${e.mark}</span>` : ''}
        </div>
        <div class="hp-bar"><div class="hp-fill" style="width:${(e.hp / e.maxHp) * 100}%"></div></div>
        <div class="fig-name">${e.def.name} <span class="hp-num">${e.hp}/${e.maxHp}</span></div>
      `;
      fig.onclick = () => onFigureTap(e.uid);
      slot.appendChild(fig);
    }
    enemyHalf.appendChild(slot);
  });
}

// Threads: gold lines between the party figures that share one.
function renderThreads(newKey) {
  const svg = $('#thread-layer');
  svg.innerHTML = '';
  if (!S || S.node.chapter < 2) return;
  const stageR = $('#stage').getBoundingClientRect();
  const scale = stageR.width / 760;
  S.threads.forEach(key => {
    const [a, b] = key.split('|');
    const ea = figEl(a), eb = figEl(b);
    if (!ea || !eb) return;
    const ra = ea.getBoundingClientRect(), rb = eb.getBoundingClientRect();
    const bf = $('#battlefield').getBoundingClientRect();
    const x1 = (ra.left + ra.width / 2 - bf.left) / scale;
    const y1 = (ra.top + ra.height * 0.45 - bf.top) / scale;
    const x2 = (rb.left + rb.width / 2 - bf.left) / scale;
    const y2 = (rb.top + rb.height * 0.45 - bf.top) / scale;
    const midY = Math.min(y1, y2) - 22;
    const path = document.createElementNS('http://www.w3.org/2000/svg', 'path');
    path.setAttribute('d', `M ${x1} ${y1} Q ${(x1 + x2) / 2} ${midY} ${x2} ${y2}`);
    path.setAttribute('class', 'thread-line' + (key === newKey ? ' thread-new' : ''));
    svg.appendChild(path);
  });
}

function renderActionBar() {
  $('#ep-num').textContent = S.ep;
  $('#ep-max').textContent = '/' + S.maxEp;
  $('#btn-endturn').disabled = S.executing || S.over;

  const handEl = $('#hand');
  handEl.innerHTML = '';
  if (S.over) return;
  const TYPE_LABEL = { attack: '✕ ATTACK', guard: '⛨ GUARD', skill: '✦ SKILL', move: '⇄ MOVE', resonant: '✦ RESONANT' };
  buildHand().forEach(card => {
    const type = cardType(card);
    const el = document.createElement('div');
    el.className = `card kind-${card.kind}`
      + (card.spent ? ' card-spent' : (card.cost > S.ep ? ' disabled' : ''));
    if (card.kind === 'resonant' && S.resonantNew) el.classList.add('card-burn-in');
    el.style.setProperty('--tint', card.tint);
    el.innerHTML = `
      <div class="c-top">
        <span class="c-cost">${card.cost}</span>
        <span class="c-name">${card.name}</span>
      </div>
      <div class="c-type t-${type}">${TYPE_LABEL[type]}</div>
      <div class="c-desc">${card.desc}</div>
      <div class="c-owner"><span>${card.ownerName}</span><span class="c-stance">· ${card.stance}</span></div>
    `;
    el.onclick = () => onCardTap(card);
    handEl.appendChild(el);
  });
  if (S.resonantNew) S.resonantNew = false;

  // Fan the hand when it outgrows the strip (mock: "cards fan — drag to
  // play").  Cards overlap just enough to fit; hover/tap raises one above
  // its neighbours via the .card:hover z-index rule.
  requestAnimationFrame(() => {
    const kids = [...handEl.children];
    if (kids.length < 2) return;
    const avail = handEl.clientWidth;
    let total = 0;
    kids.forEach(k => { total += k.offsetWidth + 6; });
    if (total > avail) {
      const overlap = Math.min(86, (total - avail) / (kids.length - 1));
      kids.forEach((k, i) => {
        if (i > 0) k.style.marginLeft = (-overlap) + 'px';
        k.style.zIndex = i + 1;
      });
    }
  });
}

// ---------------------------------------------------------------------------
// FX helpers
// ---------------------------------------------------------------------------
function popupAt(el, text, cls) {
  if (!el) return;
  const layer = $('#popup-layer');
  const stageR = $('#stage').getBoundingClientRect();
  const scale = stageR.width / 760;
  const r = el.getBoundingClientRect();
  const p = document.createElement('div');
  p.className = 'popup ' + (cls || '');
  p.textContent = text;
  p.style.left = ((r.left + r.width / 2 - stageR.left) / scale) + 'px';
  p.style.top = ((r.top - stageR.top) / scale + 6) + 'px';
  layer.appendChild(p);
  setTimeout(() => p.remove(), 1050);
}
function shake(el) {
  if (!el) return;
  el.classList.remove('fig-hit'); void el.offsetWidth; el.classList.add('fig-hit');
}
let _narrTimer = null;
function flashNarrator(text) {
  $('#narrator').textContent = text || '';
  clearTimeout(_narrTimer);
  if (text) _narrTimer = setTimeout(() => { $('#narrator').textContent = ''; }, 4200);
}

// ---------------------------------------------------------------------------
// OVERLAY / TITLE / GATE
// ---------------------------------------------------------------------------
function showOverlay(html, extraClass) {
  const ov = $('#overlay');
  ov.className = extraClass || '';
  ov.classList.remove('hidden');
  $('#overlay-inner').innerHTML = html;
}
function hideOverlay() {
  $('#overlay').classList.add('hidden');
  $('#overlay').onclick = null;
}

function showTitle() {
  S = null;
  $('#timeline').innerHTML = '';
  const saved = parseInt(localStorage.getItem(PROGRESS_KEY) || '0', 10) || 0;
  showOverlay(`
    <div class="ov-title">KIZUNA</div>
    <div class="ov-sub">THREADS · VERSION 2 PROTOTYPE</div>
    <div class="ov-line" style="text-align:center; max-width:420px; margin:0 auto 20px;">
      The party is the character. Cards are how three people talk;
      <b>the thread between them</b> is what you’re playing.
    </div>
    <button class="ov-btn primary" id="t-new">NEW GAME</button>
    ${saved > 0 ? `<button class="ov-btn" id="t-continue">CONTINUE</button>` : ''}
    <div class="ov-hint">V2 BUILD ${V2_BUILD} · V1 LIVES AT THE ROOT URL</div>
  `);
  $('#t-new').onclick = () => { flowIdx = 0; try { localStorage.setItem(PROGRESS_KEY, '0'); } catch (_) {} startFlowNode(); };
  const c = $('#t-continue');
  if (c) c.onclick = () => { flowIdx = saved; startFlowNode(); };
}

function showGate() {
  showOverlay(`
    <div class="ov-title" style="font-size:24px">KIZUNA</div>
    <div class="ov-sub">THREADS</div>
    <div class="gate-card">
      <input type="password" id="gate-input" autocomplete="off" placeholder="…" />
      <button class="ov-btn primary" id="gate-go">ENTER</button>
      <div class="gate-err" id="gate-err"></div>
    </div>
  `);
  const tryIt = () => {
    if (($('#gate-input').value || '').toLowerCase() === 'keeter') {
      try { localStorage.setItem(UNLOCK_KEY, '1'); } catch (_) {}
      showTitle();
    } else { $('#gate-err').textContent = 'incorrect'; $('#gate-input').value = ''; }
  };
  $('#gate-go').onclick = tryIt;
  $('#gate-input').addEventListener('keydown', e => { if (e.key === 'Enter') tryIt(); });
  setTimeout(() => $('#gate-input').focus(), 60);
}

// ---------------------------------------------------------------------------
// FIT-TO-SCREEN + BOOT
// ---------------------------------------------------------------------------
function fitStage() {
  const w = window.innerWidth, h = window.innerHeight;
  const scale = Math.min(w / 760, h / 430);
  $('#stage').style.transform = `scale(${scale})`;
}
window.addEventListener('resize', fitStage);
window.addEventListener('orientationchange', () => setTimeout(fitStage, 120));

// Cancel targeting on any stray tap outside a valid figure.
document.addEventListener('pointerdown', (e) => {
  if (!targeting) return;
  if (e.target.closest('.fig-targetable') || (targeting.isRow && e.target.closest('.slot'))) return;
  cancelTargeting();
}, true);

$('#btn-endturn').addEventListener('click', endTurn);

fitStage();
let unlocked = false;
try { unlocked = localStorage.getItem(UNLOCK_KEY) === '1'; } catch (_) {}
if (unlocked) showTitle(); else showGate();
